### ISSUE TITLE
Client crashes if cavedust finishes in study

### ISSUE THREAD

**Issue by puruscor** [puruscor/Purus-Pasta#19]
```
2.24.1:${gitrev}

java.lang.NullPointerException
   at haven.Curiosity.LPH(Curiosity.java:88)
   at haven.CharWnd$StudyInfo.upd(CharWnd.java:750)
   at haven.AttnMeter.draw(AttnMeter.java:25)
   at haven.Widget.draw(Widget.java:690)
   at haven.Widget.draw(Widget.java:695)
   at haven.Widget.draw(Widget.java:690)
   at haven.Widget.draw(Widget.java:695)
   at haven.GameUI.draw(GameUI.java:756)
   at haven.Widget.draw(Widget.java:690)
   at haven.Widget.draw(Widget.java:695)
   at haven.RootWidget.draw(RootWidget.java:67)
   at haven.UI.draw(UI.java:152)
   at haven.HavenPanel.rootdraw(HavenPanel.java:348)
   at haven.HavenPanel.run(HavenPanel.java:608)
   at java.lang.Thread.run(Unknown Source)
```

**Comment by puruscor** [comment]
Fixed
