### ISSUE TITLE
Hovering on Bloated Bolete lags

### ISSUE THREAD

**Issue by ghandhikus** [puruscor/Purus-Pasta#2]
After hovering on Bloated Bolete the whole client froze.

**Comment by puruscor** [comment]
Could you try this using build.zip and running run_debug.bat and pasting possible error log?

**Comment by ghandhikus** [comment]
Try to catch all exceptions and send them to log server.

Pull-request https://github.com/puruscor/Purus-Pasta/pull/3

Exception in thread "Haven UI thread" java.lang.ArithmeticException: / by zero
        at haven.Curiosity.LPE(Curiosity.java:83)
        at haven.Curiosity.tipimg(Curiosity.java:64)
        at haven.ItemInfo$Tip.layout(ItemInfo.java:118)
        at haven.ItemInfo$Layout.render(ItemInfo.java:91)
        at haven.ItemInfo.longtip(ItemInfo.java:279)
        at haven.WItem.longtip(WItem.java:61)
        at haven.WItem.longtip(WItem.java:69)
        at haven.WItem$LongTip.<init>(WItem.java:100)
        at haven.WItem.tooltip(WItem.java:135)
        at haven.Widget.tooltip(Widget.java:1021)
        at haven.Widget.tooltip(Widget.java:1021)
        at haven.Window.tooltip(Window.java:329)
        at haven.Widget.tooltip(Widget.java:1021)
        at haven.Widget.tooltip(Widget.java:1021)
        at haven.HavenPanel.rootdraw(HavenPanel.java:360)
        at haven.HavenPanel.run(HavenPanel.java:585)
        at java.lang.Thread.run(Unknown Source)
